### ISSUE TITLE
 Edit Available Services' Page (Valeria)

### ISSUE THREAD

**Issue by tiffsoa** [v3r1510/Service_Manager_Website#7]
Description: Design the detailed page for each selected service with information and links to businesses.

Tasks:
- Add service name, description, and company names that offer the service.
- Include pricing and call-to-action buttons.

**Comment by v3r1510** [comment]
Instead of having specific services page, we decided to display the necessary details and booking / CTA buttons on the same page where all the available services can be seen.
- Redesign layout to match with the other pages (e.g. admin dashboard)
- Create booking button on each service
- Display price for every service
- Add search bar functionality
